version: '3.4'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vemodev
  
  vemoapi:
    image: vemoapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
        - postgres
    volumes:
      - "../../../frontend/public/PhotoProfile:/app/PhotoProfile"