version: '3.4'

services:
  vemoapi:
    image: satputraya/vemoapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=vemodev;Username=postgres;Password=postgres;"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    depends_on:
        - postgres
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vemodev
    