version: '3.4'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vemodev
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  vemoapi:
    image: vemoapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
        - postgres
    volumes:
      - "/home/vemo/app/frontend/dist/PhotoProfile:/app/PhotoProfile"
